### ISSUE TITLE
Very big values appearing

### ISSUE THREAD

**Issue by mpasserini** [jhammond/lltop#2]
I've been running LLTOP on a production Lustre system, and I noticed that every once in a while there are extremely high values appearing, I wonder if there's some counter which overflows or something alike. This is an example output, we run LLTOP with an interval of 50 seconds:

CLIENT-or-JOBID     WR_MB    RD_MB    CLOSE  XRENAME     GETA    GETXA     LINK    MKDIR    MKNOD     OPEN   RENAME    RMDIR  SRENAME     SETA    SETXA     STAT     SYNC   UNLINK      OWNER NODES
1495209          138110882       54      256        0     1538    80928        0        0      192   283331        0        0        0        0        0        0      657     1009    someuser 62
1495165            111456        2      310        0     1732        0        0        0        0      310        0        0        0        0        0        0     1939        0    someuser 62
1495208             93836        3      260        0     1254        0        0        0        0     8540        0        0        0        0        0        0      722        0    someuser 52

This would mean that with the job in the first row, the user was writing at 138110882/50= 2,3TB/s ,which is not possible on out system.

Do you have any idea of why this is happening?

**Comment by jhammond** [comment]
This is likely due to a known limitation of lltop. All of the ssh sub-processes are writing into a single pipe. So there may be some interleaving of partial writes that cause lines to be corrupted.

I'm sorry to say that I have no plans to fix this. Have you looked at using xltop instead.

**Comment by mpasserini** [comment]
Thanks! 
So, I guess from your reply that xltop is not affected by this, I could try it out. Do you plan to keep supporting xltop?

**Comment by jhammond** [comment]
Correct, xltop is not affected.

I don't actively develop xltop. But I will accept and review PRs for it.
